1 cdecl hid_proxy_enumerate(long long) 
2 cdecl hid_proxy_error(ptr) 
3 cdecl hid_proxy_exit() 
4 cdecl hid_proxy_free_enumeration(ptr) 
5 cdecl hid_proxy_init() 
6 cdecl hid_proxy_open(long long wstr) 
7 cdecl hid_proxy_open_path(str) 
8 cdecl hid_proxy_close(ptr) 
9 cdecl hid_proxy_send_feature_report(ptr ptr long) 
10 cdecl hid_proxy_get_feature_report(ptr ptr long) 